services:
  - type: web
    name: voyage
    runtime: java
    plan: free
    buildCommand: |
      wget https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
      tar xzf apache-maven-3.8.4-bin.tar.gz
      export PATH=$PATH:$PWD/apache-maven-3.8.4/bin
      mvn clean package
    startCommand: java -jar target/voyage.war
    envVars:
      - key: JAVA_VERSION
        value: 8